CREATE TABLE EMP
(empno INT,ename VARCHAR(25),job VARCHAR(12),salary INT,commission INT,deptno INT);
SELECT * FROM EMP;
DESCRIBE EMP;
INSERT INTO EMP VALUES(7399,'SMITH','CLERK',800,NULL,20);
SELECT *FROM EMP;
INSERT INTO EMP(empno,ename,job,salary,commission,deptno)VALUES(7499,'ALLEN','SALESMAN',1600,300,30),
(7521,'WARD','SALESMAN',1250,500,30),
(7566,'JHONS','MANAGER',2975,NULL,20),
(7654,'MARTIN','SALESMAN',1250,1400,30),
(7698,'BLAKE',' MANAGER',2850,NULL,30),
(7782,'CLARK','MANAGER',2450,NULL,10),
(7788,'SCOTT','ANALYST',3000,NULL,20),
(7839,'KING','PRESIDENT',5000,NULL,10),
(7844,'TURNER','SALESMAN',1500,NULL,30),
(7876,'ADAMS','CLERK',1100,NULL,20),
(7900,'JAMES','NULL',950,NULL,30),
(7902,'FORD','ANALYST',3000,NULL,20),
(7934,'MILLER','CLERK',1300,NULL,10);
SELECT *FROM EMP;
UPDATE EMP SET job='CLERK'WHERE job='NULL';
SELECT * FROM EMP;
ALTER TABLE EMP
ADD COLUMN date_join varchar(50);
DESCRIBE EMP;
SELECT *FROM EMP;
UPDATE EMP 
SET date_join='17-DEC-80' WHERE empno='7399';
UPDATE EMP 
SET date_join='20-FEB-81' WHERE empno='7499';
UPDATE EMP 
SET date_join='22-FEB-81' WHERE empno='7521';
UPDATE EMP 
SET date_join='02-APR-81' WHERE empno='7566';
UPDATE EMP 
SET date_join='28-SEP-81' WHERE empno='7654';
UPDATE EMP 
SET date_join='01-MAY-81' WHERE empno='7698';
UPDATE EMP 
SET date_join='09-JUN-81' WHERE empno='7782';
UPDATE EMP 
SET date_join='19-APR-87' WHERE empno='7788';
UPDATE EMP 
SET date_join='17-NOV-81' WHERE empno='7839';
UPDATE EMP 
SET date_join='08-SEP-81' WHERE empno='7844';
UPDATE EMP 
SET date_join='23-MAY-87' WHERE empno='7876';
UPDATE EMP 
SET date_join='03-DEC-81' WHERE empno='7900';
UPDATE EMP 
SET date_join='03-DEC-81' WHERE empno='7902';
UPDATE EMP 
SET date_join='23-JAN-82' WHERE empno='7934';
SELECT * FROM EMP;
SELECT DISTINCT JOB FROM EMP;
SELECT ename,deptno FROM EMP WHERE deptno IN (20,30);
SELECT ename,salary+commission AS TOTAL_OF_SALARY FROM EMP;
SELECT ENAME,SALARY*12 AS ANNUAL_SALARY FROM EMP;
SELECT ENAME FROM EMP WHERE DATE_JOIN='03-DEC-81';
SELECT ename,salary+IFNULL(commission,0) AS TOTAL_OF_SALARY FROM EMP WHERE ENAME='MILLER';
DELETE FROM EMP WHERE ENAME='MILLER';
SELECT * FROM EMP;
SELECT ENAME,DEPTNO FROM EMP;
ALTER TABLE EMP ADD COLUMN TOTAL_SALARY NUMERIC;
UPDATE EMP SET TOTAL_SALARY=(SALARY +IFNULL(COMMISSION,0));
ALTER TABLE EMP DROP COLUMN COMMISSION;
SELECT *FROM EMP;
SELECT E.ENAME,E.SALARY FROM EMPLOYEE E INNER JOIN EMPLOYEE B ON E.SALARY=B.SALARY AND E.ENAME<>B.ENAME;
SELECT ENAME AS NAME,EMPNO AS EMP_ID FROM EMP;
RENAME TABLE EMP TO EMPLOYEE;
DESCRIBE EMPLOYEE;
CREATE TABLE EMP_TAB AS SELECT * FROM EMPLOYEE;
DESCRIBE EMP_TAB;
SELECT distinct e.empno,e.ename,e.job,e.salary,e.deptno,e.date_join,e.total_salary,
b.empno,b.ename,b.job,b.salary,b.deptno,b.date_join,b.total_salary FROM EMP_TAB e  JOIN 
EMPLOYEE b where e.empno=b.empno;
TRUNCATE TABLE EMPLOYEE;
SELECT * FROM EMPLOYEE;
DROP TABLE EMPLOYEE;